import 'package:flutter/material.dart';

const classes = [
  {
    "number": 1,
    "level": "beginner",
    "image": "assets/home_screen/alphabets.png",
    "title": "First Steps in Berlin",
    "color": Color.fromARGB(255, 255, 184, 203),
    "subColor": Color.fromARGB(255, 202, 83, 115),
    "topics": [
      {
        "number": 1,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Greetings",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Introducing Yourself",
        "image": "assets/home_screen/numbers.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Asking Questions",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Personal Pronouns",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Basic Verbs",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Definite and Indefinite Articles",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
  {
    "number": 2,
    "level": "beginner",
    "image": "assets/home_screen/list.png",
    "title": "Exploring the City",
    "color": Color.fromARGB(255, 197, 187, 245),
    "subColor": Color.fromARGB(255, 104, 95, 146),
    "topics": [
      {
        "number": 1,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Everyday Activities",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Leisure Activities",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Time Phrases",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Days of the Week",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Present Tense Conjugation",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
  {
    "number": 3,
    "level": "beginner",
    "image": "assets/home_screen/list.png",
    "title": "Dining & Shopping",
    "color": Color.fromARGB(255, 137, 243, 144),
    "subColor": Color.fromARGB(255, 62, 169, 105),
    "topics": [
      {
        "number": 1,
        "title": "Introduction",
        "image": "assets/home_screen/list.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Food & Drinks",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Shopping Terms",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Asking for Prices",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Polite Requests",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Numbers",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Negation",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
];
