import 'package:flutter/material.dart';

const classes = [
  {
    "number": 1,
    "image": "assets/home_screen/alphabets.png",
    "title": "Basics",
    "color": Color.fromARGB(255, 255, 184, 203),
    "subColor": Color.fromARGB(255, 202, 83, 115),
    "topics": [
      {
        "title": "Alphabets",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": true,
      },
      {
        "title": "Numbers",
        "image": "assets/home_screen/numbers.png",
        "isFirst": false,
        "isLast": false,
        "isPast": true,
      },
      {
        "title": "Something",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
  {
    "number": 2,
    "image": "assets/home_screen/list.png",
    "title": "Articles",
    "color": Color.fromARGB(255, 197, 187, 245),
    "subColor": Color.fromARGB(255, 104, 95, 146),
    "topics": [
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
  {
    "number": 3,
    "image": "assets/home_screen/list.png",
    "title": "Grammar",
    "color": Color.fromARGB(255, 137, 243, 144),
    "subColor": Color.fromARGB(255, 62, 169, 105),
    "topics": [
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "title": "Something else",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ],
  },
];
